export class HttpEndpoints {
  static WALLET_REGISTER = '/wallet/register';
  static WALLET_UPDATE = '/wallet/update';
  static ASSET_DEFAULT = '/asset/defaults';
  static ASSET_SEARCH = '/asset/search';
  static ASSET_DELETE = '/asset/delete';
  static ASSET_UPDATE = '/asset/update';
  static CONNECTION_INVITE = '/connection/invite';
  static CONNECTION_ACCEPT = '/connection/accept';
  static CONNECTION_REJECT = '/connection/reject';
  static CONNECTION_CANCEL = '/connection/cancel';
  static CONNECTION_BLOCK = '/connection/block';
  static CONNECTION_MUTE = '/connection/mute';
  static USER_UPDATE = '/user/update';
  static USER_INFO = '/user/info';
  static USER_SEARCH = '/user/search';
  static USER_DELETE = '/user/delete';
  static NOTIFICATION_LIST = '/notification/list';
}
