export enum HttpEndpoints {
  WALLET_REGISTER = '/wallet/register',
  WALLET_UPDATE = '/wallet/update',
  ASSET_DEFAULT = '/asset/defaults',
  ASSET_SEARCH = '/asset/search',
  ASSET_LIST = '/asset/list',
  CONNECTION_INVITE = '/connection/invite',
  CONNECTION_ACCEPT = '/connection/accept',
  CONNECTION_REJECT = '/connection/reject',
  CONNECTION_CANCEL = '/connection/cancel',
  CONNECTION_BLOCK = '/connection/block',
  CONNECTION_MUTE = '/connection/mute',
  NOTIFICATION_LIST = '/notification/list',
  USER_UPDATE = '/user/update',
  USER_INFO = '/user/info',
  USER_SEARCH = '/user/search',
  USER_DELETE = '/user/delete',
  USER_USERNAME_SEARCH = '/user/search-username',
}
