version: 2
jobs:
  build:
    working_directory: ~/pillarwallet-nodejs-sdk
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet-nodejs-sdk/.npmrc
      - run:
            name: set Registry
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Install
          command: yarn install
      - run:
          name: Install TypeScript packages globally
          command: sudo yarn global add typescript tsc ts-node
      - run:
          name: Compile TypeScript to JS
          command: tsc
  test:
    working_directory: ~/pillarwallet-nodejs-sdk
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Test
          command: echo please write some unit-tests
  publish:
    working_directory: ~/pillarwallet-nodejs-sdk
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "console.log( require('./package.json').version )")-$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet-nodejs-sdk/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish   --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: workflowCi
